In [1]:
import numpy as np
import pandas as pd
import h5py
import os
from tqdm.notebook import tqdm

# from methods.data_proc import downscale
from methods.io_things import tar_to_downscaled_models

# CURR_DIR = os.getcwd()

ROCKS = pd.read_excel('rock_properties.xlsx', index_col=0)




In [2]:
ROCKS

Lithology Lithology class Genetic class  \
Fels_Dyke_Sill   Felsic_Dyke_Sill            Dyke     Intrusive   
Maf_Dyke_Sill     Mafic_Dyke_Sill            Dyke     Intrusive   
Granite                   Granite            Plug     Intrusive   
Peridotite             Peridotite            Plug     Intrusive   
Porphyry                 Porphyry            Plug     Intrusive   
Pyxenite_Hbnd    Pyxenite_Hbndite            Plug     Intrusive   
Gabbro                     Gabbro            Plug     Intrusive   
Diorite                   Diorite            Plug     Intrusive   
Syenite                   Syenite            Plug     Intrusive   
Amphib                Amphibolite       Met_strat   Metamorphic   
Gneiss                     Gneiss       Met_strat   Metamorphic   
Marble                     Marble       Met_strat   Metamorphic   
Meta_Carb          Meta_Carbonate       Met_strat   Metamorphic   
Meta_Felsic           Meta_Felsic       Met_strat   Metamorphic   
Meta_Intermed   Meta_Intermediate       Met_strat   Metamorphic   
Meta_Mafic             Meta_Mafic       Met_strat   Metamorphic   
Meta_Sediment       Meta_Sediment       Met_strat   Metamorphic   
Meta_Ultramaf     Meta_Ultramafic       Met_strat   Metamorphic   
Schist                     Schist       Met_strat   Metamorphic   
Andesite                 Andesite       Met_strat      Volcanic   
Basalt                     Basalt       Met_strat      Volcanic   
Dacite                     Dacite       Met_strat      Volcanic   
Ign_V_Breccia       Ign_V_Breccia       Met_strat      Volcanic   
Rhyolite                 Rhyolite       Met_strat      Volcanic   
Tuff_Lapillist  Tuff_Lapillistone       Met_strat      Volcanic   
V_Breccia               V_Breccia       Met_strat      Volcanic   
V_Conglomerate     V_Conglomerate       Met_strat      Volcanic   
V_Sandstone           V_Sandstone       Met_strat      Volcanic   
V_Siltstone           V_Siltstone       Met_strat      Volcanic   
Conglomerate         Conglomerate           Strat   Sedimentary   
Limestone               Limestone           Strat   Sedimentary   
Pelite                     Pelite           Strat   Sedimentary   
Phyllite                 Phyllite           Strat   Sedimentary   
Sandstone               Sandstone           Strat   Sedimentary   
Greywacke               Greywacke           Strat   Sedimentary   

                Mean density (g cm−3)  Std density  \
Fels_Dyke_Sill               2.612593     0.090526   
Maf_Dyke_Sill                2.793914     0.015760   
Granite                      2.691577     0.094590   
Peridotite                   2.851076     0.154478   
Porphyry                     2.840024     0.128972   
Pyxenite_Hbnd                3.194379     0.253323   
Gabbro                       3.004335     0.159719   
Diorite                      2.851608     0.134657   
Syenite                      2.685824     0.115078   
Amphib                       2.875933     0.142164   
Gneiss                       2.701191     0.073584   
Marble                       2.871775     0.532997   
Meta_Carb                    2.738965     0.036720   
Meta_Felsic                  2.782584     0.301452   
Meta_Intermed                2.894892     0.265154   
Meta_Mafic                   2.814461     0.096382   
Meta_Sediment                2.982992     0.494396   
Meta_Ultramaf                2.843941     0.138208   
Schist                       2.819780     0.109753   
Andesite                     2.721189     0.091639   
Basalt                       2.792690     0.155153   
Dacite                       2.621270     0.129131   
Ign_V_Breccia                2.910459     0.101746   
Rhyolite                     2.630833     0.071234   
Tuff_Lapillist               2.644470     0.110174   
V_Breccia                    2.771579     0.167796   
V_Conglomerate               2.755267     0.103883   
V_Sandstone                  2.779715     0.101133   
V_Siltstone                  2.859347     0.1

In [2]:
# PATH_TO_MODELS = 'D:/geological_models/' # path to folder with TAR files like "DYKE_FOLD_FOLT" and others
PATH_TO_MODELS = 'temp/'
NMODELS = 5

yield_path = tar_to_downscaled_models(PATH_TO_MODELS, NMODELS)

  0%|          | 0/3 [00:00<?, ?it/s]

Extracting ==> temp/DYKE_DYKE_DYKE.tar
Done


  0%|          | 0/5 [00:00<?, ?it/s]

Extracting ==> temp/DYKE_DYKE_FAULT.tar
Done


  0%|          | 0/5 [00:00<?, ?it/s]

Extracting ==> temp/DYKE_DYKE_FOLD.tar
Done


  0%|          | 0/5 [00:00<?, ?it/s]

In [4]:
# и вот наш файл с проницаемостями
with h5py.File(yield_path, 'r') as f:
    perm = f['/perm'][0]
    dens = f['/dens'][0]

print(perm)

[[[31.81 31.81 31.81 ... 31.81 31.86 32.28]
  [31.81 31.81 31.81 ... 31.88 32.22 32.34]
  [29.81 32.   31.81 ... 32.25 32.34 32.34]
  ...
  [43.1  32.75 32.34 ... 53.8  53.8  53.62]
  [32.34 32.34 34.5  ... 53.8  49.44 30.2 ]
  [32.34 35.16 50.38 ... 39.1  26.95 44.44]]

 [[31.81 31.81 31.81 ... 31.88 32.22 32.34]
  [30.69 31.81 31.81 ... 32.2  32.34 32.34]
  [25.75 32.72 31.86 ... 32.34 32.34 32.16]
  ...
  [32.75 32.34 34.1  ... 53.8  53.8  47.72]
  [32.34 34.6  47.7  ... 52.47 37.16 28.19]
  [36.44 48.97 53.78 ... 28.12 37.25 52.47]]

 [[31.19 31.81 31.81 ... 32.25 32.34 32.34]
  [26.28 31.39 31.81 ... 32.34 32.34 32.16]
  [25.02 29.39 33.9  ... 32.34 32.12 31.83]
  ...
  [32.34 34.62 47.75 ... 53.8  50.7  33.  ]
  [36.56 48.97 53.78 ... 41.94 27.14 41.6 ]
  [52.12 53.8  53.8  ... 32.7  50.5  53.8 ]]

 ...

 [[41.03 32.47 32.34 ... 31.81 31.81 31.81]
  [32.47 32.34 34.25 ... 31.81 31.81 31.81]
  [32.34 35.06 48.7  ... 31.81 31.81 31.81]
  ...
  [53.8  53.8  53.8  ... 25.42 30.23 52.